# vim: set ft=ansible:
---
- name: Configure the security groups
  hosts: localhost
  gather_facts: no
  connection: local
  sudo: no
  tasks:
  - name: Create ec2 vpc
    ec2_vpc:
      state: present
      dns_support: yes
      dns_hostnames: yes
      cidr_block: 172.18.0.0/16
      resource_tags:
        env: "{{ cluster_id }}"
      region: "{{ ec2_region }}"
      subnets:
      - cidr: 172.18.1.0/24
      internet_gateway: yes
      route_tables:
      - subnets:
        - 172.18.1.0/24
        routes:
        - dest: 0.0.0.0/0
          gw: igw
      wait: yes
    register: vpc
