# vim: set ft=ansible:
---
- name: Launch the instance
  hosts: localhost
  gather_facts: no
  connection: local
  sudo: no
  vars_files:
  - ../vars.yml
  vars:
    host_groups: "{{ provider_defaults.ec2.groups }}"
    host_tags: "{{ provider_defaults.ec2.tags }}"
    master_groups: "{{ provider_defaults.ec2.master.groups }}"
    master_tags: "{{ provider_defaults.ec2.master.tags }}"
    master_security_groups: "{{ provider_defaults.ec2.master.security_groups }}"
  tasks:
  - fail:
      msg: required values not set
    when: ec2_region is not defined or cluster_id is not defined or ec2_image is not defined or ec2_keypair is not defined or ec2_master_instance_type is not defined or r53_host_zone is not defined

  - set_fact:
      os_type: master
      security_groups: "{{ master_security_groups }}"
      instance_groups: "{{  host_groups | union(master_groups) | unique }}"
      instance_tags: "{{  host_tags | oo_dict_merge(master_tags) }}"
      volumes:
      - volume_size: 15
        device_type: gp2
        device_name: /dev/sda1
        delete_on_termination: True
      - device_name: /dev/xvdb
        device_type: gp2
        volume_size: 25
        delete_on_termination: True
      - device_name: /dev/xvdc
        device_type: gp2
        volume_size: 25
        delete_on_termination: True

  - name: Create ec2 instance
    ec2:
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      key_name: "{{ ec2_keypair }}"
      instance_type: "{{ ec2_master_instance_type }}"
      group: "{{ security_groups }}"
      user_data: "{{ lookup('template', '../templates/user_data_master.j2') }}"
      exact_count: 1
      wait: yes
      count_tag: "{{ instance_tags }}"
      instance_tags: "{{ instance_tags }}"
      volumes: "{{ volumes }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes
    register: ec2

  - name: Add name tag to instances
    ec2_tag: resource={{ item.id }} region={{ ec2_region }} state=present
    args:
      tags:
        Name: "openshift-master.{{ r53_host_zone }}"
    when: item.state == "running"
    with_items: ec2.instances

  - name: Create host dns entry
    route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "openshift-master.{{ r53_host_zone }}"
      ttl: 60
      type: A
      value: "{{ item.public_ip }}"
      overwrite: yes
    when: r53_host_zone and item.state == 'running'
    with_items: ec2.instances

  - name: Add new instance groups and variables
    add_host:
      hostname: "openshift-master.{{ r53_host_zone }}"
      ansible_ssh_host: "{{ item.dns_name }}"
      ansible_ssh_user: openshift
      groups: "{{ instance_groups | join(', ') }}"
      ec2_private_ip_address: "{{ item.private_ip }}"
      ec2_ip_address: "{{ item.public_ip }}"
      ec2_tag_node-region: master
      ec2_tag_Name: "openshift-master.{{ r53_host_zone }}"
    when: item.state == "running"
    with_items: ec2.instances

  - name: Wait for ssh
    wait_for: "port=22 host={{ item.dns_name }}"
    when: item.state == "running"
    with_items: ec2.instances

  - name: Wait for user setup
    command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null openshift@{{ item.dns_name }} echo openshift user is setup"
    register: result
    until: result.rc == 0
    retries: 20
    delay: 10
    when: item.state == "running"
    with_items: ec2.instances
