# vim: set ft=ansible:
---
- name: Setting up smoke projects...
  hosts: oo_first_master
  vars_files:
  - ../vars.yml
  tasks:
  # Set up the smoke project and app
  - name: Create user smoke test projects
    command: "oadm new-project {{ item }}-smoke --display-name='Smoke Test' --admin={{ item }}"
    when: item not in projects.stdout
    with_sequence: start=0 end=40 format=user%02d

  - name: Create "app" in smoke projects
    command: "oc new-app openshift/php~https://github.com/gshipley/smoke.git -n {{ item }}-smoke"
    when: item not in projects.stdout
    with_sequence: start=0 end=40 format=user%02d

  - name: Expose smoke project service
    command: "oc expose service smoke -n {{ item }}-smoke"
    when: item not in projects.stdout
    with_sequence: start=0 end=40 format=user%02d

  - name: Wait to scale smoke app for first deployment
    shell: "oc get rc --all-namespaces | grep smoke | wc -l"
    register: build_output
    until: build_output.stdout.find("41") != -1
    retries: 11
    delay: 30

  - name: Scale smoke app
    command: "oc scale dc/smoke --replicas=2 -n {{ item }}-smoke"
    when: item not in projects.stdout
    with_sequence: start=0 end=40 format=user%02d


