# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  tasks:
  - fail:
      msg: required values not set
    when: cluster_id is not defined or ec2_region is not defined or ec2_image is not defined or ec2_keypair is not defined or ec2_master_instance_type is not defined or ec2_infra_instance_type is not defined or ec2_node_instance_type is not defined or r53_zone is not defined or r53_host_zone is not defined or r53_wildcard_zone is not defined or num_app_nodes is not defined or hexboard_size is not defined or api_port is not defined or console_port is not defined or rhsm_user is not defined or rhsm_pass is not defined or deployment_type is not defined

# Add the created hosts to groups for configuration
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars_files:
  - vars.yml
  vars:
    master_hosts: "{{ groups['tag_openshift-master_' ~ cluster_id] }}"
    node_hosts: "{{ groups['tag_openshift-node_' ~ cluster_id] }}"
  tasks:
  - add_host:
      name: "{{ item }}"
      ansible_ssh_user: openshift
      ansible_sudo: yes
      deployment_type: "{{ deployment_type }}"
      groups: oo_masters_to_config, oo_first_master
      openshift_public_hostname: "{{ hostvars[item]['ec2_tag_Name'] }}"
      openshift_cluster_id: "{{ cluster_id }}"
      openshift_debug_level: "{{ debug_level }}"
      openshift_deployment_type: "{{ deployment_type }}"
      openshift_master_access_token_max_seconds: 2419200
      openshift_master_identity_providers: "{{ identity_providers }}"
      openshift_master_api_port: "{{ api_port }}"
      openshift_master_console_port: "{{ console_port }}"
      osm_cluster_network_cidr: 10.0.0.0/8
      osm_host_subnet_length: 16
      osm_default_subdomain: "{{ r53_wildcard_zone }}"
      osm_default_node_selector: "region={{ os_defaults.regions.1.name }}"
    with_items: master_hosts
  - add_host:
      name: "{{ item }}"
      ansible_ssh_user: openshift
      ansible_sudo: yes
      deployment_type: "{{ deployment_type }}"
      groups: oo_nodes_to_config
      openshift_cluster_id: "{{ cluster_id }}"
      openshift_debug_level: "{{ debug_level }}"
      openshift_deployment_type: "{{ deployment_type }}"
      openshift_public_hostname: "{{ hostvars[item]['ec2_tag_Name'] }}"
      openshift_node_labels:
        region: "{{ hostvars[item]['ec2_tag_node-region'] }}"
        zone: default
      openshift_node_kubelet_args:
        max-pods:
        - "100"
      openshift_node_sdn_mtu: 1450
    with_items: node_hosts

# Smoke projects
- name: Setting up smoke projects...
  hosts: oo_first_master
  vars_files:
  - vars.yml
  tasks:
  - include: tasks/smoke_projects.yml
    when: run_smoke_tests | bool
