# vim: set ft=ansible:
---
- name: Register host(s)
  hosts: cluster_hosts
  serial: 1
  gather_facts: no
  tasks:
  - name: Register host
    redhat_subscription:
      username: "{{ rhsm_user }}"
      password: "{{ rhsm_pass }}"
      state: present
      pool: "^(60 Day Supported OpenShift Enterprise|OpenShift Enterprise, Standard|OpenShift Enterprise, Premium|Employee)"
    register: register_result
    when: not (skip_subscription_management | bool)

  - name: Disable all known rhsm repos
    command: subscription-manager repos --disable='*'
    when: register_result | changed

  - name: Subscribe only to the ose repo
    command: subscription-manager repos --enable=rhel-7-server-ose-3.1-rpms
    when: register_result | changed

- name: Repository configuration
  hosts: cluster_hosts
  gather_facts: yes
  tasks:
  - name: Enable rhui extras channel
    command: yum-config-manager --enable rhui-REGION-rhel-server-extras

  - include: ../../aos-ansible/playbooks/roles/ops_mirror_bootstrap/tasks/main.yml
    vars:
      omb_aos_repo: "{{ aos_repo }}"
    when: use_certificate_repos | bool

  - name: Disable rhel-72 prerelease repo when not prerelease
    command: yum-config-manager --disable rhel-72
    when: not prerelease | bool

  - name: Disable rhel-72-extras prerelease repo when not prerelease
    command: yum-config-manager --disable rhel-72-extras
    when: not prerelease | bool

  - include: ../../aos-ansible/playbooks/roles/qe_registry_bootstrap/tasks/main.yml
    vars:
      omb_aos_repo: "{{ aos_repo }}"
      qe_openshift_kerberos_user: "{{ kerberos_user }}"
      qe_openshift_token: "{{ kerberos_token }}"
    when: use_certificate_repos | bool and prerelease | bool


